364569 cleanup: firmware_wget()

diff --git a/etc/kalua/firmware b/etc/kalua/firmware
--- a/etc/kalua/firmware
+++ b/etc/kalua/firmware
@@ -476,13 +476,19 @@ _firmware_upgrade_is_needed()
 
 _firmware_wget()
 {
+	local funcname="firmware_wget"
 	local hash="07af7c0202648bd06676d26c27550d26"
 	local source="http://intercity-vpn.de/firmware/ar71xx/images/testing/openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-sysupgrade.bin"
 	local file="${1:-/tmp/fw}"
 
-	[ -e "$file" ] && return 0
+	[ -e "$file" ] && return 0		# fixme!
 
-	while [ "$( md5sum "$file" | cut -d" " -f1 )" != "$hash" ]; do {
+	filehash_is_ok()
+	{
+		test "$( _file hash "$file" )" = "$hash"
+	}	
+
+	while ! filehash_is_ok ; do {
 		_log do fetch_firmware daemon info "http_get $source"
 		wget -qcO "$file" "$source"
 		sleep 1
@@ -490,8 +496,10 @@ _firmware_wget()
 	} done
 
 	if _watch counter "/tmp/fetch_firmware" increment 1 max 100; then
+		_log do $funcname daemon info "[READY] downloading '$file'"
 		return 0
 	else
+		_log do $funcname daemon info "[ERR] downloading '$file', maximum tries reached, deleting and aborting"
 		rm "$file" /tmp/fetch_firmware
 		return 1
 	fi
