361544 insmod() do not alert-log error during conntrack* on kernel2.6

diff --git a/etc/kalua/system b/etc/kalua/system
--- a/etc/kalua/system
+++ b/etc/kalua/system
@@ -368,6 +368,7 @@ _system_insmod ()
 	local FUNC="system_insmod"
 	local KMOD="$1"
 	local OPTIONS="$2"
+	local logprio
 
 	lsmod | grep -q ^$KMOD && return	# already loaded
 
@@ -406,7 +407,17 @@ _system_insmod ()
 
 		_log do $FUNC daemon debug "[OK] memoryusage: ${MEM_DIFF} bytes (lsmod: '$( lsmod | grep ^$KMOD )$( lsmod | grep ^${CHANGED_PREFIX_KMOD:-prefix_is_unset} )')"
 	else
-		_log do $FUNC daemon alert "[ERR] failing to insert kernel-module '${KMOD}.o' returned with $?"
+		logprio="alert"
+
+		_uci is_oldstyle || {
+			case "$KMOD" in
+				ip_conntrack*)			# fixme! kernel2.6 seems different
+					logprio="debug"
+				;;
+			esac
+		}
+
+		_log do $FUNC daemon $logprio "[ERR] failing to insert kernel-module '${KMOD}.o' returned with $?"
 		
 		local FILE
 		FILE="$( find /lib/modules/ | grep ${KMOD}.o )"			# e.g. /lib/modules/2.4.30/ipt_length.o 
