363877 minor fix in system_insmod() (returncode was not correctly detected)

diff --git a/etc/kalua/system b/etc/kalua/system
--- a/etc/kalua/system
+++ b/etc/kalua/system
@@ -384,14 +384,16 @@ _system_insmod ()
 	local MEM_BEFORE="$( _system ram_free )"
 	local MEM_AFTER=0
 	local MEM_DIFF=0
+	local rc
 
 	_log do $FUNC daemon info "[TRY] insmod \"$KMOD\" \"$OPTIONS\""
 	insmod "$KMOD" "$OPTIONS" || {
 		_log do $FUNC daemon info "[TRY] insmod \"$CHANGED_PREFIX_KMOD\" \"$OPTIONS\""
 		insmod "$CHANGED_PREFIX_KMOD" "$OPTIONS"
 	}
+	rc=$?
 
-	if [ $? -eq 0 ] ; then
+	if [ $rc -eq 0 ] ; then
 
 		case "$KMOD" in
 			crondog)
@@ -417,7 +419,7 @@ _system_insmod ()
 			esac
 		}
 
-		_log do $FUNC daemon $logprio "[ERR] failing to insert kernel-module '${KMOD}.o' returned with $?"
+		_log do $FUNC daemon $logprio "[ERR] failing to insert kernel-module '${KMOD}.o' returned with $rc"
 		
 		local FILE
 		FILE="$( find /lib/modules/ | grep ${KMOD}.o )"			# e.g. /lib/modules/2.4.30/ipt_length.o 
