kalua: init: crashlog_apport: dont upload crash twice

diff --git a/openwrt-addons/etc/init.d/crashlog_apport b/openwrt-addons/etc/init.d/crashlog_apport
--- a/openwrt-addons/etc/init.d/crashlog_apport
+++ b/openwrt-addons/etc/init.d/crashlog_apport
@@ -145,12 +145,13 @@ start()
 		} done
 
 		[ $maxtry -eq 0 ] && {
-			destination="/www/crashlog.$( cat /proc/uptime ).$$"
-			cat "$file" >"$destination"
-			echo "upload crash failed, wrote to: '$destination'" >>/www/everlasting_syslog.txt
+			destination="/www/crashlog.$( _file hash "$file" )"
+			[ -e "$destination" ] || {
+				cat "$file" >"$destination"
+				echo "upload crash failed, wrote to: '$destination'" >>'/www/everlasting_syslog.txt'
 
-			echo >>$SCHEDULER "/etc/init.d/$funcname start upload_crash"
+				echo >>$SCHEDULER "/etc/init.d/$funcname start upload_crash"
+			}
 		}
 	} done
 }
-
