351447 weblogin: ignore overload detection when load caused by bad SSL handshakes

diff --git a/www/cgi-bin-welcome b/www/cgi-bin-welcome
--- a/www/cgi-bin-welcome
+++ b/www/cgi-bin-welcome
@@ -2,9 +2,11 @@
 
 [ "$REQUEST_METHOD" != "POST" ] && {		# allow login, but deny skype/whatever knockings
 	IFS='. '; read CPULOAD DECIMALS NOP </proc/loadavg; unset IFS
-	[ $CPULOAD -gt 5 ] && {
-		echo -en "Content-type: text/html\n\n<html><head><title>Weblogin error</title></head><body><big><br>&nbsp;Netzwerk-&Uuml;berlastung - bitte 3 Minuten warten.<br>&nbsp;Network overload - please wait 3 minutes.</big><br><br><small>&nbsp;&nbsp;technical info:<br>&nbsp;&nbsp;load is $CPULOAD.$DECIMALS (must be < 1.00)</small></body></html>"
-		exit
+	[ $CPULOAD -gt 1 ] && {
+		[ "$( tail -n50 /var/log/messages | fgrep "SSL handshake failed" | wc -l )" -gt 10 ] || {
+			echo -en "Content-type: text/html\n\n<html><head><title>Weblogin error</title></head><body><big><br>&nbsp;Netzwerk-&Uuml;berlastung - bitte 3 Minuten warten.<br>&nbsp;Network overload - please wait 3 minutes.</big><br><br><small>&nbsp;&nbsp;technical info:<br>&nbsp;&nbsp;load is $CPULOAD.$DECIMALS (must be < 1.00)</small></body></html>"
+			exit
+		}
 	}
 }
 
