kalua: db: generate_grepable_index() let the 'check' call work, even if db_restore() was not called yet (so symlinking works again)

diff --git a/openwrt-addons/etc/kalua/db b/openwrt-addons/etc/kalua/db
--- a/openwrt-addons/etc/kalua/db
+++ b/openwrt-addons/etc/kalua/db
@@ -280,15 +280,29 @@ _db_backup()		# fixme! automatically call this after <prio> changes
 	return $errorcode
 }
 
-_db_generate_grepable_index()
+db_generate_grepable_index()
 {
 	local funcname='db_generate_grepable_index'
-	local option="$1"
+	local option="$1"	# <empty> or 'check'
 	local file='/tmp/USERDB_COPY.cgi.gz'
 	local file_index="$DIR_DATABASE/USER/login/meta_index"
+	local file_symlink='/www/USERDB_COPY.txt'
 	local logprio='info'
 	local marker_ok='# OK'
-	local size
+
+	[ "$option" = 'check' ] && {
+		_weblogin authserver is_myself && {
+			# is it really a working link? see: /www/cgi-bin-get_userdb.sh
+			# if restore failed, we have at least a working link
+			ls -1 "$file_symlink" 2>/dev/null >/dev/null || {
+				rm 2>/dev/null "$file_symlink"
+				ln -s "$file"  "$file_symlink"
+			}
+		}
+
+		# only generate index if missing/too small
+		test -s "$file" && return 0
+	}
 
 	[ -e "$file_index" ] || {
 		# we cannot work if db_restore() was not fired yet:
@@ -297,36 +311,29 @@ _db_generate_grepable_index()
 		return 1
 	}
 
-	[ "$option" = 'check' ] && {
-		size=$( _file size "$file" )
-		[ $size -gt 0 ] && return 0
-	}
-
 	do_index()
 	{
-		# why tac? it's likely, that we grep for a new login - this should match faster
-		# this is >1 magnitude faster than sed-tac
-		# fixme! ATM it limits to ~1mb size (4000 lines)
+		local lines=4000	# FIXME! ATM it limits to ~1mb size (4000 lines)
+
+		# include all free mac's ("important")
 		grep ' mac: ' "$file_index"
+
+		# include all commented entries ("important")
 		grep '  comment: ' "$file_index"
-		grep -n '' "$file_index" | sort -rn | cut -d: -f2- | head -n 4000
+
+		# simulate 'tac' = oldest lines first, because
+		# it's likely, that we grep for a new login - this matches faster
+		# this method is >1 magnitude faster than sed-tac
+		grep -n '' "$file_index" | sort -rn | cut -d: -f2- | head -n $lines
+
+		# clients will check for the end-marker
 		echo "$marker_ok"
 	}
 
-	do_index	>"/tmp/USERDB_COPY.cgi"
-	rm 2>/dev/null	"$file"
-	gzip		'/tmp/USERDB_COPY.cgi'		# will append .gz
-	rm		'/tmp/USERDB_COPY.cgi'
+	do_index | gzip	>"$file"
 
-	# is it really a working link? see: cgi-bin-get_userdb.sh
-	ls -1 '/www/USERDB_COPY.txt' 2>/dev/null >/dev/null || {
-		rm 2>/dev/null 	'/www/USERDB_COPY.txt'
-		ln -s "$file" 	'/www/USERDB_COPY.txt'
-	}
-
-	size=$( _file size "$file" )
-	[ $size -gt 0 ] || logprio='alert'
-	_log do $funcname daemon $logprio "[OK] copy size: $size bytes"
+	test -s $file || logprio='alert'
+	_log do $funcname daemon $logprio "[OK] copy size: $( _file size "$file" ) bytes"
 }
 
 _db_restore()
@@ -374,6 +381,7 @@ _db_restore()
 					sed -i "/''[^']''/s/''/'/g" "$DIR_DATABASE/USER/device/rows"
 				}
 
+				# force new index
 				_db generate_grepable_index
 			else
 				_log do $funcname daemon alert "[ERR] untar of '$file' went wrong - rescheduling"
@@ -722,6 +730,7 @@ _db_user()			# poormens_db: each line has: ID=<integer>;A="";B="";C="";D="";...;
 				_db lock free
 			fi
 
+			# force new index
 			_db generate_grepable_index
 		;;
 		list)
