kalua: firmware: download() add 'is_running' marker at function start (not later)

diff --git a/openwrt-addons/etc/kalua/firmware b/openwrt-addons/etc/kalua/firmware
--- a/openwrt-addons/etc/kalua/firmware
+++ b/openwrt-addons/etc/kalua/firmware
@@ -1146,6 +1146,8 @@ _firmware_download()
 	elif [ -e "$file" ]; then
 		# for manually fetching the file and test the whole procedure
 		return 0
+	else
+		touch "$marker"		# TODO: add a cleanup-trap
 	fi
 
 	local source="${2:-$( _links firmware_url_get )}"	# url
@@ -1156,6 +1158,7 @@ _firmware_download()
 
 	[ ${#hash} -eq 32 ] || {
 		_log it $funcname daemon info "abort - hash invalid: '$hash'"
+		rm "$marker"
 		return 1
 	}
 
