kalua: vpn: innercity: activate new style on master - autoconnect when local_inet_offer (cached now)

diff --git a/openwrt-addons/etc/kalua/vpn b/openwrt-addons/etc/kalua/vpn
--- a/openwrt-addons/etc/kalua/vpn
+++ b/openwrt-addons/etc/kalua/vpn
@@ -280,7 +280,9 @@ _vpn_hideandseek_master_vtund_write_config()
 	local file="${1:-/tmp/vtund.conf}"
 	local name="Node$NODENUMBER"
 
-	[ -e "$file" ] || cat >"$file" <<EOF
+	[ -e "$file" ] && return 1
+
+	cat >"$file" <<EOF
 $name {
 	passwd ff ;
 	type ether ;
@@ -329,56 +331,73 @@ _vpn_hideandseek_vtund()
 
 _vpn_x()
 {
-if [ -e '/tmp/vtund.sh' ]; then
-	# todo: use a function and more varnames
-	# maybe better?: grep "tap[0-9]:" /proc/net/dev
-	if pidof vtund >/dev/null; then
-		logread >'/tmp/logread.out'
-
-		dev_has_probs()
-		{
-			if ip address show dev "$1" | grep -q 'inet6 '; then
-				return 1
-			else
-				return 0
-			fi
-		}
-
-		restart_vtund()
-		{
-			_log do check_vtund daemon alert "restarting: $1"
-			killall vtund
-			. '/tmp/vtund.sh'
-		}
-
-		if   dev_has_probs 'tap0'; then
-			restart_vtund "dev is not fully up"
-		elif grep -q 'Connection timed out' '/tmp/logread.out'; then
-			[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep 'Connection timed out' '/tmp/logread.out' | wc -l ) -gt 5 ] && {
-				grep -q ' vtund: link_up ' '/tmp/logread.out' || {
-					restart_vtund "our pubip has changed?"
+	if [ -e '/etc/vtund.conf' ]; then
+		case "$( head -n1 '/etc/vtund.conf' )" in
+			# oldstyle or default-conf
+			*'4.v.weimarnetz.de'*|'#')
+				_net local_inet_offer cached >/dev/null && {
+					_vpn hideandseek_vtund check_on_client
+					return 0
 				}
-			}
-		elif grep -q "Can't resolv server address" '/tmp/logread.out'; then
-			[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep "Can't resolv server address" '/tmp/logread.out' | wc -l ) -gt 5 ] && {
-				restart_vtund "servers pubip has changed?"
-			}
-		fi
-
-		rm '/tmp/logread.out'
+			;;
+		esac
 	else
-		_log do check_vtund daemon alert "starting up after crash"
-		. '/tmp/vtund.sh'
-	fi
-else
-	[ -e "/etc/vtund.conf" ] && {			# startup-code must be a comment at first line
-		grep -q ^'# vtund ' "/etc/vtund.conf" && {
-			head -n1 "/etc/vtund.conf" | cut -b 2- >"/tmp/vtund.sh"
-
-			_log do check_vtund daemon info "starting up"
-			. '/tmp/vtund.sh'
+		_net local_inet_offer cached >/dev/null && {
+			_vpn hideandseek_vtund check_on_client
+			return 0
 		}
-	}
-fi
+	fi
 
+	# oldstyle or e.g. special config:
+	if [ -e '/tmp/vtund.sh' ]; then
+		# todo: use a function and more varnames
+		# maybe better?: grep "tap[0-9]:" /proc/net/dev
+		if pidof vtund >/dev/null; then
+			logread >'/tmp/logread.out'
+
+			dev_has_probs()
+			{
+				if ip address show dev "$1" | grep -q 'inet6 '; then
+					return 1
+				else
+					return 0
+				fi
+			}
+
+			restart_vtund()
+			{
+				_log do check_vtund daemon alert "restarting: $1"
+				killall vtund
+				. '/tmp/vtund.sh'
+			}
+
+			if   dev_has_probs 'tap0'; then
+				restart_vtund "dev is not fully up"
+			elif grep -q 'Connection timed out' '/tmp/logread.out'; then
+				[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep 'Connection timed out' '/tmp/logread.out' | wc -l ) -gt 5 ] && {
+					grep -q ' vtund: link_up ' '/tmp/logread.out' || {
+						restart_vtund "our pubip has changed?"
+					}
+				}
+			elif grep -q "Can't resolv server address" '/tmp/logread.out'; then
+				[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep "Can't resolv server address" '/tmp/logread.out' | wc -l ) -gt 5 ] && {
+					restart_vtund "servers pubip has changed?"
+				}
+			fi
+
+			rm '/tmp/logread.out'
+		else
+			_log do check_vtund daemon alert "starting up after crash"
+			. '/tmp/vtund.sh'
+		fi
+	else
+		[ -e "/etc/vtund.conf" ] && {			# startup-code must be a comment at first line
+			grep -q ^'# vtund ' "/etc/vtund.conf" && {
+				head -n1 "/etc/vtund.conf" | cut -b 2- >"/tmp/vtund.sh"
+
+				_log do check_vtund daemon info "starting up"
+				. '/tmp/vtund.sh'
+			}
+		}
+	fi
 }
