use the correct ping value

diff --git a/openwrt-addons/etc/kalua/vpn b/openwrt-addons/etc/kalua/vpn
--- a/openwrt-addons/etc/kalua/vpn
+++ b/openwrt-addons/etc/kalua/vpn
@@ -258,27 +258,26 @@ _vpn_build_vars ()
   for i in 1 2 3 4 5 6 7 8 9 10
   do
     SERVER=$i.$PREFIX.$DOMAIN
-    PING="$( _net ping_getlatency "$SERVER" )" && {
-      URL="http://$SERVER$JSONPATH"
-      JSON=$( _wget do "$URL" )
-      if [ "$?" -ne 0 ]; then 
-         _log do $FUNC daemon err "error: Could not reach $URL"
-      else
-          #_log do $FUNC daemon notice "JSON: $JSON"
-          json_load "$JSON"
-          SERVER=     json_get_var SERVER server
-          CLIENTS=-1  json_get_var CLIENTS clients
-          MTU=-1      json_get_var MTU maxmtu
-          PORT=-1     json_get_var PORT port_vtun_${VTUNDTYPE}
-          if [ "$CLIENTS" -ge 0 ] && [ "$PORT" -ge 0 ] && [ "$MTU" -ge 0 ]; then
+    URL="http://$SERVER$JSONPATH"
+    JSON=$( _wget do "$URL" )
+    if [ "$?" -ne 0 ]; then 
+      _log do $FUNC daemon err "error: Could not reach $URL"
+    else
+       #_log do $FUNC daemon notice "JSON: $JSON"
+       json_load "$JSON"
+       SERVER=     json_get_var SERVER server
+       CLIENTS=-1  json_get_var CLIENTS clients
+       MTU=-1      json_get_var MTU maxmtu
+       PORT=-1     json_get_var PORT port_vtun_${VTUNDTYPE}
+       if [ "$CLIENTS" -ge 0 ] && [ "$PORT" -ge 0 ] && [ "$MTU" -ge 0 ]; then
               #PORT=$( _vpn vtund_port "$VTUNDTYPE" )
              _log do $FUNC daemon notice "got $SERVER as valid VPN"
+             PING="$( _net ping_getlatency "$SERVER" )" 
              TABLE="$TABLE:$PING $i $CLIENTS $MTU $PORT $SERVER"
-          else
+       else
             _log do $FUNC daemon err "error: $URL does not contain a valid VPN"
-         fi
-     fi
-    }
+       fi
+    fi
   done
 
  # get VPN with lowest latency
