kalua: vpn: hideandseek + voip: join checks

diff --git a/openwrt-addons/etc/kalua/vpn b/openwrt-addons/etc/kalua/vpn
--- a/openwrt-addons/etc/kalua/vpn
+++ b/openwrt-addons/etc/kalua/vpn
@@ -308,15 +308,17 @@ _vpn_hideandseek_vtund()
 	case "$action" in
 		check_on_client)
 			if _vpn hideandseek_master_vtund_write_config; then
-				# config written
+				# config now written
 				_vpn hideandseek_vtund fire
 			else
 				# config already there
+
 				# TODO: some daemon checks:
 				# - ping6?
 				# - activate for hideandseek if 3 times good
 				# - deactivate for hideandseek if 1 x bad
-				:
+
+				_vpn check_daemon
 			fi
 		;;
 		fire)
@@ -334,6 +336,62 @@ _vpn_hideandseek_vtund()
 			_vpn hideandseek_vtund fire
 		;;
 	esac
+}
+
+# needs better name:
+_vpn_check_daemon()
+{
+	# todo: use a function and more varnames
+	# maybe better?: grep "tap[0-9]:" /proc/net/dev
+	if pidof vtund >/dev/null; then
+		logread >'/tmp/logread.out'
+
+		dev_has_probs()
+		{
+			if ip address show dev "$1" | grep -q 'inet6 '; then
+				return 1
+			else
+				return 0
+			fi
+		}
+
+		restart_vtund()
+		{
+			_log do check_vtund daemon alert "restarting: $1"
+
+			if [ -e '/tmp/vtund.sh' ]; then
+				# oldstyle
+				killall vtund
+				. '/tmp/vtund.sh'
+			else
+				_vpn hideandseek_vtund restart
+			fi
+		}
+
+		if   dev_has_probs 'tap0'; then
+			restart_vtund 'dev is not fully up'
+		elif grep -q 'Connection timed out' '/tmp/logread.out'; then
+			[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep 'Connection timed out' '/tmp/logread.out' | wc -l ) -gt 5 ] && {
+				grep -q ' vtund: link_up ' '/tmp/logread.out' || {
+					restart_vtund 'our pubip has changed?'
+				}
+			}
+		elif grep -q "Can't resolv server address" '/tmp/logread.out'; then
+			[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep "Can't resolv server address" '/tmp/logread.out' | wc -l ) -gt 5 ] && {
+				restart_vtund 'servers pubip has changed?'
+			}
+		fi
+
+		rm '/tmp/logread.out'
+	else
+		_log do check_vtund daemon alert "starting up after crash"
+
+		if [ -e '/tmp/vtund.sh' ]; then
+			. '/tmp/vtund.sh'
+		else
+			_vpn hideandseek_vtund start
+		fi
+	fi
 }
 
 _vpn_x()
@@ -357,46 +415,7 @@ _vpn_x()
 
 	# oldstyle or e.g. special config:
 	if [ -e '/tmp/vtund.sh' ]; then
-		# todo: use a function and more varnames
-		# maybe better?: grep "tap[0-9]:" /proc/net/dev
-		if pidof vtund >/dev/null; then
-			logread >'/tmp/logread.out'
-
-			dev_has_probs()
-			{
-				if ip address show dev "$1" | grep -q 'inet6 '; then
-					return 1
-				else
-					return 0
-				fi
-			}
-
-			restart_vtund()
-			{
-				_log do check_vtund daemon alert "restarting: $1"
-				killall vtund
-				. '/tmp/vtund.sh'
-			}
-
-			if   dev_has_probs 'tap0'; then
-				restart_vtund "dev is not fully up"
-			elif grep -q 'Connection timed out' '/tmp/logread.out'; then
-				[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep 'Connection timed out' '/tmp/logread.out' | wc -l ) -gt 5 ] && {
-					grep -q ' vtund: link_up ' '/tmp/logread.out' || {
-						restart_vtund "our pubip has changed?"
-					}
-				}
-			elif grep -q "Can't resolv server address" '/tmp/logread.out'; then
-				[ $( grep "vtund\[[0-9]*\]:" '/tmp/logread.out' | grep "Can't resolv server address" '/tmp/logread.out' | wc -l ) -gt 5 ] && {
-					restart_vtund "servers pubip has changed?"
-				}
-			fi
-
-			rm '/tmp/logread.out'
-		else
-			_log do check_vtund daemon alert "starting up after crash"
-			. '/tmp/vtund.sh'
-		fi
+		_vpn check_daemon
 	else
 		[ -e "/etc/vtund.conf" ] && {			# startup-code must be a comment at first line
 			grep -q ^'# vtund ' "/etc/vtund.conf" && {
