appendix: variable name bracket consistence

diff --git a/openwrt-addons/etc/kalua/vpn b/openwrt-addons/etc/kalua/vpn
--- a/openwrt-addons/etc/kalua/vpn
+++ b/openwrt-addons/etc/kalua/vpn
@@ -333,34 +333,34 @@ _vpn_build_vars ()
               2>/dev/null ]; 
             then
              _log do ${FUNC} daemon notice "got ${SERVER} - ping: ${PING}ms"
-             TABLE="$TABLE;$PING $i $CLIENTS $MTU $PORT $SERVER"
+             TABLE="${TABLE};${PING} ${i} ${CLIENTS} ${MTU} ${PORT} ${SERVER}"
        else
-            _log do $FUNC daemon err "error: invalid data on $URL"
+            _log do ${FUNC} daemon err "error: invalid data on ${URL}"
        fi
     fi
   done
 
 # no vpn, then exit early
-[ -n "$TABLE" ] || return 1
+[ -n "${TABLE}" ] || return 1
 
 # get VPN with lowest latency
 # warning: leading spaces somehow break this
 read PING NUMBER CLIENTS MTU PORT SERVER <<EOF 
-  $( echo $TABLE | tr ';' '\n' | sed '/^$/d' | sort -n | head -n1 )
+  $( echo ${TABLE} | tr ';' '\n' | sed '/^$/d' | sort -n | head -n1 ) # TODO?
 EOF
 
- VPN_SERVER="$SERVER"
+ VPN_SERVER="${SERVER}"
 
- _log do $FUNC daemon notice "using $VPN_SERVER - ping: ${PING}ms  clients: $CLIENTS  port: $PORT  mtu: $MTU"
+ _log do ${FUNC} daemon notice "using ${VPN_SERVER} - ping: ${PING}ms  clients: ${CLIENTS}  port: ${PORT}  mtu: ${MTU}"
  NODE_NUMBER="$( uci -q get system.@profile[0].nodenumber )"
  HOSTNAME="$( uci -q get system.@system[0].hostname )"
- [ -z "$HOSTNAME" ] && HOSTNAME="node$NODE_NUMBER"
- SERV="$VPN_SERVER"	# _ip4|_ip6 fallback?
+ [ -z "${HOSTNAME}" ] && HOSTNAME="node${NODE_NUMBER}"
+ SERV="${VPN_SERVER}"	# _ip4|_ip6 fallback?
  CONF="/var/etc/olsrd.conf"			# old_style
- KNOT=$NODE_NUMBER
+ KNOT="${NODE_NUMBER}"
  VTUN="/tmp/vtund.conf"
 
- [ "$1" != "stop" ] && INETOFFER=$( _net local_inet_offer )
+ [ "${1}" != "stop" ] && INETOFFER="$( _net local_inet_offer )"
 	
  eval "$( _ipsystem do )"
 }
