kalua: weblogin: authserver_message() auto-reschedule if it fails

diff --git a/openwrt-addons/etc/kalua/weblogin b/openwrt-addons/etc/kalua/weblogin
--- a/openwrt-addons/etc/kalua/weblogin
+++ b/openwrt-addons/etc/kalua/weblogin
@@ -879,9 +879,12 @@ _weblogin_authserver_message()
 {
 	local message="$1"
 	local server="$( _weblogin authserver )"
+	local url_message="$( _sanitizer do "$message" urlvalue )"
 
-	message="$( _sanitizer do "$message" urlvalue )"
-	_wget do "http://$server/cgi-bin-tool.sh?OPT=message&MSG=$message"
+	_wget do "http://$server/cgi-bin-tool.sh?OPT=message&MSG=$url_message" || {
+		# reschedule if it fails
+		echo >>$SCHEDULER "_weblogin authserver_message $message"
+	}
 }
 
 _weblogin_authserver_ask()
