kalua: wget: do() simplify cleanup of tempfiles via trap

diff --git a/openwrt-addons/etc/kalua/wget b/openwrt-addons/etc/kalua/wget
--- a/openwrt-addons/etc/kalua/wget
+++ b/openwrt-addons/etc/kalua/wget
@@ -46,6 +46,10 @@ _wget_do()
 
 	# get pids and fire the real 'wget':
 	list_wget_pids_initial="$( pidof wget )"
+
+	# autocleanup tempfiles. trapping 'RETURN' is not possible in POSIX
+	trap "rm /tmp/${funcname}_$mypid /tmp/${funcname}_$mypid.error" EXIT
+
 	( wget $proxy_command -qO $filename $file_option "$url" 2>"/tmp/${funcname}_$mypid.error" || echo "$?" >"/tmp/${funcname}_$mypid" ) &
 	pid_background=$!
 	list_wget_pids_after_launch="$( pidof wget )" || list_wget_pids_after_launch=$(( pid_background + 2 ))
@@ -54,17 +58,9 @@ _wget_do()
 	# remove, when the 'too early exit' bug is found
 #	_log do $funcname daemon debug "pids: initial: '$list_wget_pids_initial' background: '$pid_background' after: '$list_wget_pids_after_launch'"
 
-	element_in_list()
-	{
-		local element="$1"
-		local list="$2"
-
-		echo " $list " | grep -q " $element "
-	}
-
 	# join PIDs initial + after_launch
 	for element in $list_wget_pids_after_launch; do {
-		element_in_list "$element" "$list_wget_pids_initial" || {
+		_list contains_element "$list_wget_pids_initial" "$element" || {
 			list_wget_pids_myself="$list_wget_pids_myself $element"
 		}
 	} done
@@ -75,9 +71,7 @@ _wget_do()
 		break
 	} done
 
-	read myerror 2>/dev/null <"/tmp/${funcname}_$$.error" && {
-		rm "/tmp/${funcname}_$$.error"
-
+	read myerror 2>/dev/null <"/tmp/${funcname}_$mypid.error" && {
 		if [ ${#myerror} -eq 0 ]; then
 			_log do $funcname daemon debug '[OK] no error message'
 		else
@@ -153,9 +147,7 @@ _wget_do()
 	} done
 
 	# FIXME! code duplication, see above
-	read myerror 2>/dev/null <"/tmp/${funcname}_$$.error" && {
-		rm "/tmp/${funcname}_$$.error"
-
+	read myerror 2>/dev/null <"/tmp/${funcname}_$mypid.error" && {
 		if [ ${#myerror} -eq 0 ]; then
 			_log do $funcname daemon debug '[OK] no error message'
 		else
@@ -172,8 +164,7 @@ _wget_do()
 		fi
 	}
 
-	read rc 2>/dev/null <"/tmp/${funcname}_$$" && {
-		rm "/tmp/${funcname}_$$"
+	read rc 2>/dev/null <"/tmp/${funcname}_$mypid" && {
 		_log do $funcname daemon info "[ERR] returning $rc after fetching '$url'"
 	}
 
