kalua: wifi: minstrel() disable for now (except debug-mode)

diff --git a/openwrt-addons/etc/kalua/wifi b/openwrt-addons/etc/kalua/wifi
--- a/openwrt-addons/etc/kalua/wifi
+++ b/openwrt-addons/etc/kalua/wifi
@@ -158,6 +158,12 @@ _wifi_minstrel_extract_raw_and_real_txrate_from_neigh_with_highest_success_rate(
 		;;
 	esac
 
+	# fixme! this mess needs a cleanup, so better disable for now
+	[ "$option" = 'debug' ] || {
+		echo "txrate=${rate:-0};txthroughput=${throughput:-0};efficiency=${efficiency:-0};system=${system};ip=$ip"
+		return 0
+	}
+
 	[ -e "/tmp/OLSR/LINKS.sh" ] && {
 		eval $( fgrep "REMOTE=${ip};" "/tmp/OLSR/LINKS.sh" )
 		echo -n "lq=$LQ;nlq=$NLQ;cost=$COST;"
