kalua: wifi: minstrel() mute a logmessage

diff --git a/openwrt-addons/etc/kalua/wifi b/openwrt-addons/etc/kalua/wifi
--- a/openwrt-addons/etc/kalua/wifi
+++ b/openwrt-addons/etc/kalua/wifi
@@ -224,6 +224,12 @@ _wifi_minstrel_extract_raw_and_real_txrate_from_neigh_with_highest_success_rate(
 	local ip wifi_dev phy line result targetline rate throughput efficiency system file
 	local max=0
 
+	[ "$option" = 'debug' ] || {
+#		_log it minstrel_out daemon debug "FIXME - cleanup needed, use 'debug' for override"
+		echo "txrate=${rate:-0};txthroughput=${throughput:-0};efficiency=${efficiency:-0};system=${system};ip=$ip"
+		return 0
+	}
+
 	case "$mac" in
 		*':'*)
 			ip="$( _net mac2ip "$mac" )"
@@ -235,12 +241,6 @@ _wifi_minstrel_extract_raw_and_real_txrate_from_neigh_with_highest_success_rate(
 			}
 		;;
 	esac
-
-	[ "$option" = 'debug' ] || {
-		_log it minstrel_out daemon debug "FIXME - cleanup needed, use 'debug' for override"
-		echo "txrate=${rate:-0};txthroughput=${throughput:-0};efficiency=${efficiency:-0};system=${system};ip=$ip"
-		return 0
-	}
 
 	[ -e '/tmp/OLSR/LINKS.sh' ] && {
 		eval $( fgrep "REMOTE=${ip};" '/tmp/OLSR/LINKS.sh' )
